#!/bin/sh
# Screen grabber/auto paster
#
# Lets you select an area of the screen with the mouse, then automatically
# pastes a screenshot of that area to a public server and puts the URL in the
# clipboard for you. Can also open the URL in a browser and automatically
# middle-click paste the URL as soon as it's available if you want.
#
# Requires imagemagick, curl and xclip.
#
# Configure the below as appropriate for you.

# Paste site. Needs to return a redirect URI to view the file when we post to it
PASTESITE=f.dollyfish.net.nz

# Which web browser to open the paste in. Leave blank/comment out to do nothing
BROWSER=google-chrome

# Whether to automatically simulate a middle-click paste (needs xautomation)
AUTOPASTE=

# Whether to pop up a notification saying the URL has been retrieved (needs
# libnotify-bin)
NOTIFY=1

# No more configuration beyond this point
set -e


SS_DIR=/tmp
SS_FILE=screenshot.png

rm -f $SS_DIR/$SS_FILE
flameshot gui -p $SS_DIR

while events=$(inotifywait -e close_write -t 600 $SS_DIR); do
    filename=$(echo "$events" | cut -f 3 -d ' ')
    if [ "$filename" = $SS_FILE ]; then
        url=$(curl -s -w '%{redirect_url}\n' -F "file=@$SS_DIR/$SS_FILE;type=image/png" $PASTESITE)
        url=https${url#*http}
        echo $url | xclip
        [ -n "$BROWSER" ] && $BROWSER $url
        [ $AUTOPASTE ] && xte 'mouseclick 2'
        [ $NOTIFY ] && notify-send -c presence -i /usr/share/icons/hicolor/32x32/apps/checkbox.png "Image URL" "$url"
        rm $SS_DIR/$SS_FILE
        exit 0
    fi
done
